# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Time Cockpit Developer Blog
email: support@timecockpit.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.software-architects.com" # the base hostname & protocol for your site
twitter_username: timecockpit
github_username: software-architects

encoding: utf-8
plugins: [jekyll-paginate, jekyll-redirect-from, jekyll-sitemap]
paginate: 10
paginate_path: "/devblog/page:num/"
array: []

# Build settings
redirects: yes
markdown: kramdown
highlighter: rouge
encoding: utf-8
exclude: [
	software-architects-website.sln,
	package.json,
	node_modules
]
